### PR TITLE
Canopen for d1

### PR DESCRIPTION
**Pull request by Johannes-Thiel**
The D1 by Igus provides some functionality that is useful for the fieldfriend.
This Module will implement some of these functions:
- [x] setup of the Motor
- [x] homing of the Motor
- [x] speed mode 
- [x] position mode
- [x] error handling
- [x] return useful motor data
- [ ] automate the data using pdos

### CODE REVIEW

**Comment by rodja** [comment]
@pascalzauberzeug I think you successfully tested the current state today. I would suggest we as @falkoschindler to review the code, merge it and do the pdo automations on a separate pull request.

**Comment by pascalzauberzeug** [comment]
@rodja No, actually we just ran the motors via the D1 web interface

**Comment by Johannes-Thiel** [comment]
Sadly i dont get the PDOs to work.

**Comment by Johannes-Thiel** [comment]
this is working properly on f15 and on the testboard

**Review by falkoschindler — APPROVED** [review]

**Pull request merged**
